### PR TITLE
2022 q3 release dev01

### PR DESCRIPTION
**Pull request by midran**

### CODE REVIEW

**Comment by midran** [comment]
There was conflict on the release notes file. I removed the following text which needs to be added after the pull request has been accepted.

<<<<<<< 2022-q3-release-dev01
* Correction in Rule PEPPOL-COMMON-R050 (validation of Australian Business Number (ABN)) corrected
* Adopted EN 16931 validation artefacts release 1.3.9
** Added EAS codes 0217 and 9959
** Removed EAS codes 9906 and 9907
** Added ICD codes 0217, 0218, 0219 and 0220
** Correction to validation rules as listed https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/tag/validation-1.3.9
=======

== Changes to Country-Specific Rules
* Rules GR-S-008-1, GR-R-008-2 and GR-R-008-3 have been updated, expecting the string \\##INVOICE|URL## instead of \\##INVOICE-URL## (POAC-518)
* Rule DK-R-015 removed
>>>>>>> 2022-q3-release-candidate

**Comment by midran** [comment]
<<<<<<< 2022-q3-release-dev01
* Correction in Rule PEPPOL-COMMON-R050 (validation of Australian Business Number (ABN)) corrected
* Adopted EN 16931 validation artefacts release 1.3.9
** Added EAS codes 0217 and 9959
** Removed EAS codes 9906 and 9907
** Added ICD codes 0217, 0218, 0219 and 0220
** Correction to validation rules as listed https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/tag/validation-1.3.9
=======

== Changes to Country-Specific Rules
* Rules GR-S-008-1, GR-R-008-2 and GR-R-008-3 have been updated, expecting the string \\##INVOICE|URL## instead of \\##INVOICE-URL## (POAC-518)
* Rule DK-R-015 removed
>>>>>>> 2022-q3-release-candidate

**Comment by midran** [comment]
Modified the comment with the conflicting release note text by removing 0217

**Review by jerouris — CHANGES_REQUESTED** [review]
Update the sch header files to point to the correct date of the last update

**Review by jerouris — COMMENTED** [review]
Please confirm that the order type additions are properly referenced in the release notes

**Review by jerouris — APPROVED** [review]

**Pull request merged**
